name: fwfh_chewie
version: 0.14.7
description: WidgetFactory extension to render VIDEO with the chewie plugin.
homepage: https://github.com/daohoangson/flutter_widget_from_html
publish_to: 'none'
environment:
  flutter: ">=3.7.0"
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  chewie: 
    git:
      url: https://github.com/pierre-softimpact/chewie.git
      ref: master
  flutter:
    sdk: flutter
  flutter_widget_from_html_core: 
    git:
      url: https://github.com/pierre-softimpact/flutter_widget_from_html.git
      ref: master
      path: packages/flutter_widget_from_html_core
  video_player:
    git:
      url: https://github.com/icapps/plugins.git
      ref: feature/ios-pip
      path: packages/video_player/video_player

dependency_overrides:
  flutter_widget_from_html_core:
    path: ../core

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: any
  plugin_platform_interface: any
  video_player_platform_interface: ">=5.0.0 <7.0.0"

funding:
  - https://patreon.com/daohoangson
  - https://buymeacoffee.com/daohoangson

topics:
  - video
  - fwfh
